/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PqUd8;

import javax.swing.JOptionPane;

/**
 *
 * @author pedrosaura
 */
public class Ej8_16 extends javax.swing.JFrame {

    /**
     * Creates new form Ej8_16
     */
    public Ej8_16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pApuesta = new javax.swing.JPanel();
        lblImporte = new javax.swing.JLabel();
        txfImporte = new javax.swing.JTextField();
        lblEquipo = new javax.swing.JLabel();
        txfEquipo = new javax.swing.JTextField();
        pResultado = new javax.swing.JPanel();
        lblPremio = new javax.swing.JLabel();
        txfPremio = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MisApuestas.com");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pApuesta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apuesta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(214, 0, 0))); // NOI18N

        lblImporte.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblImporte.setText("Importe");

        txfImporte.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfImporte.setText("0");
        txfImporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfImporteFocusGained(evt);
            }
        });
        txfImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfImporteActionPerformed(evt);
            }
        });

        lblEquipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblEquipo.setText("Equipo");

        txfEquipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txfEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pApuestaLayout = new javax.swing.GroupLayout(pApuesta);
        pApuesta.setLayout(pApuestaLayout);
        pApuestaLayout.setHorizontalGroup(
            pApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pApuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfEquipo)
                .addContainerGap())
        );
        pApuestaLayout.setVerticalGroup(
            pApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pApuestaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pApuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporte)
                    .addComponent(txfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipo)
                    .addComponent(txfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(214, 0, 0))); // NOI18N

        lblPremio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPremio.setText("Premio");

        txfPremio.setEditable(false);
        txfPremio.setBackground(new java.awt.Color(238, 238, 238));
        txfPremio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txfPremio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfPremio.setText("0");
        txfPremio.setFocusable(false);
        txfPremio.setRequestFocusEnabled(false);
        txfPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPremioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pResultadoLayout = new javax.swing.GroupLayout(pResultado);
        pResultado.setLayout(pResultadoLayout);
        pResultadoLayout.setHorizontalGroup(
            pResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pResultadoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblPremio)
                .addGap(26, 26, 26)
                .addComponent(txfPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pResultadoLayout.setVerticalGroup(
            pResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pResultadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremio)
                    .addComponent(txfPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnVerificar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVerificar.setMnemonic('V');
        btnVerificar.setText("Verificar Premio");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(btnVerificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerificar)
                .addGap(4, 4, 4)
                .addComponent(pResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfImporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfImporteFocusGained
        // TODO add your handling code here:
        txfImporte.selectAll();
    }//GEN-LAST:event_txfImporteFocusGained

    private void txfImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfImporteActionPerformed

    private void txfEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEquipoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        //Resetear campo premio a 0
        txfPremio.setText("0");

        //Validar campo importe
        String importeCad = txfImporte.getText();
        
        int importe;
        importe = 0;
        
        try 
        {
            //Validar que importe es un número
            String importeStr = null;
            
            importe = Integer.parseInt(importeStr);
            if (importe <= 0) 
            {
                throw new NumberFormatException("Campo mayor que cero.");
            }
        } 
        catch (NumberFormatException e) 
        {
            if (e.getMessage().equals("El importe debe ser mayor que cero.")) 
            {
                JOptionPane.showMessageDialog(this, "Campo mayor que cero", "Error en importe", JOptionPane.ERROR_MESSAGE);
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Solo se admiten números", "Error en importe", JOptionPane.ERROR_MESSAGE);
            }
            txfImporte.requestFocus();
            txfImporte.selectAll();
            return;
        }

        //Obtener equipo ingresado
        String equipo = txfEquipo.getText();

        //Crear objeto ApuestaDeportiva
        ApuestaDeportiva apuesta = new ApuestaDeportiva(importe, equipo);

        //Verificar si equipo es el ganador
        if (equipo.equalsIgnoreCase("Villarreal")) 
        {
            int premio;
            premio = 10 * importe;
            
            apuesta.setPremio(premio);
            txfPremio.setText(String.valueOf(premio));
            txfEquipo.requestFocus();
            txfEquipo.selectAll();

            //Rellenar array de carac del equipo
            char[] arrLetrasEquipo = equipo.toCharArray();
            informaArray(arrLetrasEquipo, equipo);
        } 
        else 
        {
            //Limpiar campos
            txfImporte.setText("0");
            txfEquipo.setText("");
            txfPremio.setText("0");
            txfImporte.requestFocus();
            txfImporte.selectAll();
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txfPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPremioActionPerformed

    private void informaArray(char[] arrLetrasEquipo, String equipo) 
    {
        int k;
        
        for (k = 0; k < equipo.length(); k = k + 1) 
        {
            arrLetrasEquipo[k] = equipo.charAt(k);
        }
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txfImporte.requestFocus();
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej8_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej8_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej8_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej8_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej8_16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblPremio;
    private javax.swing.JPanel pApuesta;
    private javax.swing.JPanel pResultado;
    private javax.swing.JTextField txfEquipo;
    private javax.swing.JTextField txfImporte;
    private javax.swing.JTextField txfPremio;
    // End of variables declaration//GEN-END:variables
}
